// Constructor actions
export const ADD_INGREDIENT_TO_CONSTRUCTOR = 'ADD_INGREDIENT_TO_CONSTRUCTOR';
export const DELETE_INGREDIENT_FROM_CONSTRUCTOR = 'DELETE_INGREDIENT_FROM_CONSTRUCTOR';
export const CLEAR_CONSTRUCTOR = 'CLEAR_CONSTRUCTOR';
export const DELETE_BUN_FROM_CONSTRUCTOR = 'DELETE_BUN_FROM_CONSTRUCTOR';
export const SORT_INGREDIENTS_IN_CONSTRUCTOR = 'SORT_INGREDIENTS_IN_CONSTRUCTOR';