// Ingredients actions
export const GET_INGREDIENTS_SUCCESS = 'GET_INGREDIENTS_SUCCESS';
export const GET_INGREDIENTS_REQUEST = 'GET_INGREDIENTS_REQUEST';
export const GET_INGREDIENTS_FAILED = 'GET_INGREDIENTS_FAILED';
export const INGREDIENT_COUNT_INCREMENT = 'INGREDIENT_COUNT_INCREMENT';
export const INGREDIENT_COUNT_DECREMENT = 'INGREDIENT_COUNT_DECREMENT';
export const INGREDIENT_COUNT_CLEAR = 'INGREDIENT_COUNT_CLEAR';
export const INGREDIENT_COUNTS_CLEAR = 'INGREDIENT_COUNTS_CLEAR';