// Order actions
export const POST_ORDER_SUCCESS = 'POST_ORDER_SUCCESS';
export const POST_ORDER_REQUEST = 'POST_ORDER_REQUEST';
export const POST_ORDER_FAILED = 'POST_ORDER_FAILED';
export const ADD_INGREDIENT_IN_ORDER = 'ADD_INGREDIENT_IN_ORDER';
export const DELETE_INGREDIENT_FROM_ORDER = 'DELETE_INGREDIENT_FROM_ORDER';
export const CALCULATE_COAST = 'CALCULATE_COAST';
export const CLEAR_ORDER = 'CLEAR_ORDER';
export const POST_ORDER_ERROR = 'POST_ORDER_ERROR';