export const SET_USERS_DATA_SUCCESS = "SET_USERS_DATA_SUCCESS";
export const USER_REQUEST = 'USER_REQUEST';
export const USER_FAILED = 'USER_FAILED';
export const REQUEST_PASSWORD_RESET = 'REQUEST_PASSWORD_RESET';
export const USER_REQUEST_CLEAN = 'USER_REQUEST_CLEAN';
export const CLEAR_USER_STORE = 'CLEAR_USER_STORE';
export const ERROR_401 = 'ERROR_401';
